// <auto-generated />
using System;
using Combinado.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Combinado.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CombinadoDbContext))]
    [Migration("20260929170355_Onboarding_CaixaParceiroCategoria")]
    partial class Onboarding_CaixaParceiroCategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Combinado.Domain.Caixas.Caixa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_caixa");

                    b.ToTable("caixa", "public");
                });

            modelBuilder.Entity("Combinado.Domain.Caixas.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaixaId")
                        .HasColumnType("uuid")
                        .HasColumnName("caixa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<bool>("Padrao")
                        .HasColumnType("boolean")
                        .HasColumnName("padrao");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_categoria");

                    b.HasIndex("CaixaId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_categoria_caixa_slug");

                    b.ToTable("categoria", "public");
                });

            modelBuilder.Entity("Combinado.Domain.Caixas.Parceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaixaId")
                        .HasColumnType("uuid")
                        .HasColumnName("caixa_id");

                    b.Property<DateTimeOffset>("ConvidadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("convidado_em");

                    b.Property<bool>("EmailPrimario")
                        .HasColumnType("boolean")
                        .HasColumnName("email_primario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<string>("NumeroWhatsApp")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("numero_whatsapp");

                    b.Property<DateTimeOffset?>("VinculadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vinculado_em");

                    b.HasKey("Id")
                        .HasName("pk_parceiro");

                    b.HasIndex("CaixaId")
                        .HasDatabaseName("ix_parceiro_caixa_id");

                    b.HasIndex("NumeroWhatsApp")
                        .IsUnique()
                        .HasDatabaseName("ux_parceiro_numero_whatsapp");

                    b.ToTable("parceiro", "public");
                });

            modelBuilder.Entity("Combinado.Domain.Caixas.Categoria", b =>
                {
                    b.HasOne("Combinado.Domain.Caixas.Caixa", null)
                        .WithMany("Categorias")
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categoria_caixa_caixa_id");
                });

            modelBuilder.Entity("Combinado.Domain.Caixas.Parceiro", b =>
                {
                    b.HasOne("Combinado.Domain.Caixas.Caixa", null)
                        .WithMany("Parceiros")
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parceiro_caixa_caixa_id");
                });

            modelBuilder.Entity("Combinado.Domain.Caixas.Caixa", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Parceiros");
                });
#pragma warning restore 612, 618
        }
    }
}
